=== pr0z/XML5AL2K13/xsd/realestate.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            targetNamespace="http://www.xmlproject.fr" 
            xmlns="http://www.xmlproject.fr" 
            elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xsd:element name="databases">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="database" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="metaInformations" type="MetaInformations" minOccurs="1" maxOccurs="1"/>
                            <xsd:element name="tables" type="Tables" minOccurs="0" maxOccurs="1" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
	
    <xsd:complexType name="MetaInformations">
        <xsd:sequence>
            <xsd:element name="dbName" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="creatorName" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="creationDate" type="Date" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="agencyName" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="agencyAddress" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="agencyDirector" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="Tables">
        <xsd:sequence>
            <xsd:element name="properties" type="Properties" minOccurs="1" maxOccurs="1" />
            <xsd:element name="photos" type="Photos" minOccurs="1" maxOccurs="1" />
            <xsd:element name="agents" type="Agents" minOccurs="1" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="Properties">
        <xsd:sequence>
            <xsd:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="Photos">
        <xsd:sequence>
            <xsd:element name="photo" type="Photo" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="Agents">
        <xsd:sequence>
            <xsd:element name="agent" type="Agent" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="Property">
        <xsd:sequence>
            <xsd:element name="id" minOccurs="1" maxOccurs="1" type="xsd:integer" />
            <xsd:element name="name" minOccurs="1" maxOccurs="1" type="xsd:string" />
            <xsd:element name="descriptif" minOccurs="1" maxOccurs="1" type="xsd:string" />
            <xsd:element name="localisation" minOccurs="1" maxOccurs="1" type="xsd:string" />
            <xsd:element name="idAgent" minOccurs="1" maxOccurs="1" type="xsd:integer" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="Photo">
        <xsd:sequence>
            <xsd:element name="id" minOccurs="1" maxOccurs="1" type="xsd:integer" />
            <xsd:element name="idProperty" minOccurs="1" maxOccurs="1" type="xsd:integer" />
            <xsd:element name="location" minOccurs="1" maxOccurs="1" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="Agent">
        <xsd:sequence>
            <xsd:element name="id" minOccurs="1" maxOccurs="1" type="xsd:integer" />
            <xsd:element name="firstName" minOccurs="1" maxOccurs="1" type="xsd:string" />
            <xsd:element name="name" minOccurs="1" maxOccurs="1" type="xsd:string" />
            <xsd:element name="dateOfBirth" minOccurs="1" maxOccurs="1" type="Date" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:simpleType name="Date">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{2}[/]{1}[0-9]{2}[/]{1}[0-9]{4}" />
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== pr0z/XML5AL2K13/xml/realestate.xml
<?xml version="1.0" encoding="UTF-8"?>
<esgi:database
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:esgi='http://www.xmlproject.fr'
    xsi:schemaLocation='http://www.xmlproject.fr ../xsd/realestate.xsd'>
    <esgi:metaInformations>
		<esgi:dbName>realestate</esgi:dbName>
		<esgi:creatorName>roman</esgi:creatorName>
		<esgi:creationDate>23/10/2013</esgi:creationDate>
		<esgi:agencyName>KolossalAgence</esgi:agencyName>
		<esgi:agencyAddress>25 avenue de la Victoire 75008 Paris</esgi:agencyAddress>
		<esgi:agencyDirector>Paul Dupont</esgi:agencyDirector>
	</esgi:metaInformations>
	
	<esgi:tables>
		<esgi:properties>
			<esgi:property>
				<esgi:id>1</esgi:id>
				<esgi:name>Palais avenue Montaigne</esgi:name>
				<esgi:descriptif>Lorem ipsum dolor sit amet</esgi:descriptif>
				<esgi:localisation>Paris VIII</esgi:localisation>
				<esgi:idAgent>1</esgi:idAgent>
			</esgi:property>
		</esgi:properties>
		
		<esgi:photos>
			<esgi:photo>
				<esgi:id>1</esgi:id>
				<esgi:idProperty>1</esgi:idProperty>
				<esgi:location>/img/property1_img1.jpg</esgi:location>
			</esgi:photo>
		</esgi:photos>
		
		<esgi:agents>
			<esgi:agent>
				<esgi:id>1</esgi:id>
				<esgi:firstName>Thomas</esgi:firstName>
				<esgi:name>Desmarest</esgi:name>
				<esgi:dateOfBirth>14/05/1978</esgi:dateOfBirth>
			</esgi:agent>
		</esgi:agents>
	</esgi:tables>

</esgi:database>
